export const ENVIRONMENT_CONNECTION_SUCCESS = 'ENVIRONMENT_CONNECTION_SUCCESS';
export const ENVIRONMENT_CONNECTION_FAILED = 'ENVIRONMENT_CONNECTION_FAILED';
export const ENVIRONMENT_HOME_PATH_VALID = 'ENVIRONMENT_HOME_PATH_VALID';
export const ENVIRONMENT_HOME_PATH_INVALID = 'ENVIRONMENT_HOME_PATH_INVALID';

export const ENVIRONMENT_IS_OBFUSCATED = 'ENVIRONMENT_IS_OBFUSCATED';
export const ENVIRONMENT_IS_NOT_OBFUSCATED = 'ENVIRONMENT_IS_NOT_OBFUSCATED';

export const GET_EXISTING_CLIENTS_ARRAY = 'GET_EXISTING_CLIENTS_ARRAY';
export const FAILED_TO_GET_EXISTING_CLIENTS_ARRAY =
  'FAILED_TO_GET_EXISTING_CLIENTS_ARRAY';
